CREATE GROUP rw_access;

GRANT CONNECT ON DATABASE name TO rw_access;
ALTER DEFAULT PRIVILEGES GRANT DELETE, UPDATE, INSERT, SELECT ON TABLES TO rw_access;
GRANT USAGE ON SCHEMA public TO rw_access;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER ON ALL TABLES IN SCHEMA public TO rw_access;
GRANT USAGE ON ALL SEQUEENCES IN SCHEMA public TO rw_access;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO rw_access;
ALTER DEFAULT PRIVILEGES IN SCHEMA public TO rw_access;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO rw_access;